/*
 * Copyright 2026 Tobias Leikam (RheinMain University of Applied Sciences)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 */

package com.example.androidmqttclient.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * The theme has been created using the Material Theme Builder.
 * https://material-foundation.github.io/material-theme-builder/
 */
val primaryLight = Color(0xFF735187)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF5D9FF)
val onPrimaryContainerLight = Color(0xFF5A396D)
val secondaryLight = Color(0xFF735187)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF4D9FF)
val onSecondaryContainerLight = Color(0xFF5A396E)
val tertiaryLight = Color(0xFF815153)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDADA)
val onTertiaryContainerLight = Color(0xFF663B3C)
val errorLight = Color(0xFF904B40)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD4)
val onErrorContainerLight = Color(0xFF73342A)
val backgroundLight = Color(0xFFFFF7FC)
val onBackgroundLight = Color(0xFF1E1A20)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFEADFEA)
val onSurfaceVariantLight = Color(0xFF4B444D)
val outlineLight = Color(0xFF7D747E)
val outlineVariantLight = Color(0xFFCEC3CE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFFE1B8F5)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryLightMediumContrast = Color(0xFF48285C)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF835F97)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF48285C)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF835F97)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF532A2C)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF926061)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF5E241C)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFA1594D)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFFF7FC)
val onBackgroundLightMediumContrast = Color(0xFF1E1A20)
val surfaceLightMediumContrast = Color(0xFFF5FAFB)
val onSurfaceLightMediumContrast = Color(0xFF0C1213)
val surfaceVariantLightMediumContrast = Color(0xFFEADFEA)
val onSurfaceVariantLightMediumContrast = Color(0xFF3A343C)
val outlineLightMediumContrast = Color(0xFF575059)
val outlineVariantLightMediumContrast = Color(0xFF726A74)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F3)
val inversePrimaryLightMediumContrast = Color(0xFFE1B8F5)
val surfaceDimLightMediumContrast = Color(0xFFC2C7C9)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F6)
val surfaceContainerLightMediumContrast = Color(0xFFE3E9EA)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3D4)

val primaryLightHighContrast = Color(0xFF3D1E51)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF5D3C70)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF3D1E51)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF5D3C70)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF472123)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF693D3E)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF511A13)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF76362D)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFFF7FC)
val onBackgroundLightHighContrast = Color(0xFF1E1A20)
val surfaceLightHighContrast = Color(0xFFF5FAFB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEADFEA)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF302A32)
val outlineVariantLightHighContrast = Color(0xFF4E474F)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFE1B8F5)
val surfaceDimLightHighContrast = Color(0xFFB4BABB)
val surfaceBrightLightHighContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFECF2F3)
val surfaceContainerLightHighContrast = Color(0xFFDEE3E5)
val surfaceContainerHighLightHighContrast = Color(0xFFCFD5D6)
val surfaceContainerHighestLightHighContrast = Color(0xFFC2C7C9)

val primaryDark = Color(0xFFE1B8F5)
val onPrimaryDark = Color(0xFF422255)
val primaryContainerDark = Color(0xFF5A396D)
val onPrimaryContainerDark = Color(0xFFF5D9FF)
val secondaryDark = Color(0xFFE1B8F5)
val onSecondaryDark = Color(0xFF422255)
val secondaryContainerDark = Color(0xFF5A396E)
val onSecondaryContainerDark = Color(0xFFF4D9FF)
val tertiaryDark = Color(0xFFF4B7B8)
val onTertiaryDark = Color(0xFF4C2527)
val tertiaryContainerDark = Color(0xFF663B3C)
val onTertiaryContainerDark = Color(0xFFFFDADA)
val errorDark = Color(0xFFFFB4A8)
val onErrorDark = Color(0xFF561E16)
val errorContainerDark = Color(0xFF73342A)
val onErrorContainerDark = Color(0xFFFFDAD4)
val backgroundDark = Color(0xFF161217)
val onBackgroundDark = Color(0xFFE9E0E7)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF4B444D)
val onSurfaceVariantDark = Color(0xFFCEC3CE)
val outlineDark = Color(0xFF978E98)
val outlineVariantDark = Color(0xFF4B444D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF735187)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)

val primaryDarkMediumContrast = Color(0xFFF1D1FF)
val onPrimaryDarkMediumContrast = Color(0xFF36174A)
val primaryContainerDarkMediumContrast = Color(0xFFA883BC)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFF1D1FF)
val onSecondaryDarkMediumContrast = Color(0xFF36174A)
val secondaryContainerDarkMediumContrast = Color(0xFFA883BD)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFFD1D2)
val onTertiaryDarkMediumContrast = Color(0xFF3F1A1C)
val tertiaryContainerDarkMediumContrast = Color(0xFFB98384)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CB)
val onErrorDarkMediumContrast = Color(0xFF48140D)
val errorContainerDarkMediumContrast = Color(0xFFCC7B6F)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF161217)
val onBackgroundDarkMediumContrast = Color(0xFFE9E0E7)
val surfaceDarkMediumContrast = Color(0xFF0E1415)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4B444D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE4D9E4)
val outlineDarkMediumContrast = Color(0xFFB9AFB9)
val outlineVariantDarkMediumContrast = Color(0xFF968D97)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF5B3A6F)
val surfaceDimDarkMediumContrast = Color(0xFF0E1415)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4647)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040809)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F20)
val surfaceContainerDarkMediumContrast = Color(0xFF23292A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2D3435)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F40)

val primaryDarkHighContrast = Color(0xFFFCEBFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFDDB4F1)
val onPrimaryContainerDarkHighContrast = Color(0xFF170028)
val secondaryDarkHighContrast = Color(0xFFFCEBFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFDCB4F1)
val onSecondaryContainerDarkHighContrast = Color(0xFF170028)
val tertiaryDarkHighContrast = Color(0xFFFFECEB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFF0B3B4)
val onTertiaryContainerDarkHighContrast = Color(0xFF1E0305)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA1)
val onErrorContainerDarkHighContrast = Color(0xFF220000)
val backgroundDarkHighContrast = Color(0xFF161217)
val onBackgroundDarkHighContrast = Color(0xFFE9E0E7)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4B444D)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF8EDF8)
val outlineVariantDarkHighContrast = Color(0xFFCABFCA)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF5B3A6F)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF4B5152)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1B2122)
val surfaceContainerDarkHighContrast = Color(0xFF2B3133)
val surfaceContainerHighDarkHighContrast = Color(0xFF363C3E)
val surfaceContainerHighestDarkHighContrast = Color(0xFF424849)

val ConnectionGreen = Color(0xFF4CAF50)